package Login;

import Interfaces.adminInterface;
import Interfaces.clientInterface;
import Interfaces.vetInterface;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

public class LoginInterface extends javax.swing.JFrame {

    private String user;

    public LoginInterface(String user) {
        this.user = user;
        initComponents();
        centreWindow();
    }

    private void centreWindow() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y - 25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card_content = new javax.swing.JPanel();
        login_section = new javax.swing.JPanel();
        login_tittle = new javax.swing.JLabel();
        name_text = new javax.swing.JTextField();
        key_text = new javax.swing.JTextField();
        key_tittle = new javax.swing.JLabel();
        name_tittle = new javax.swing.JLabel();
        singInbutton = new javax.swing.JPanel();
        singIn_title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(400, 375));
        setPreferredSize(new java.awt.Dimension(400, 300));

        card_content.setBackground(new java.awt.Color(255, 255, 255));

        login_section.setBackground(new java.awt.Color(8, 156, 255));

        login_tittle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        login_tittle.setText("Login");
        login_section.add(login_tittle);

        key_tittle.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        key_tittle.setText("Clave");

        name_tittle.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        name_tittle.setText("Nombre");

        singInbutton.setBackground(new java.awt.Color(8, 156, 255));
        singInbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                singInbuttonMouseClicked(evt);
            }
        });

        singIn_title.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        singIn_title.setText("Iniciar");
        singInbutton.add(singIn_title);

        javax.swing.GroupLayout card_contentLayout = new javax.swing.GroupLayout(card_content);
        card_content.setLayout(card_contentLayout);
        card_contentLayout.setHorizontalGroup(
            card_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_section, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(card_contentLayout.createSequentialGroup()
                .addGroup(card_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card_contentLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(name_tittle))
                    .addGroup(card_contentLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(key_tittle))
                    .addGroup(card_contentLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(singInbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(card_contentLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(card_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name_text)
                            .addComponent(key_text, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        card_contentLayout.setVerticalGroup(
            card_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_contentLayout.createSequentialGroup()
                .addComponent(login_section, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(name_tittle)
                .addGap(22, 22, 22)
                .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(key_tittle)
                .addGap(18, 18, 18)
                .addComponent(key_text, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(singInbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(card_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(card_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void singInbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_singInbuttonMouseClicked
        String nombre = name_text.getText();
        int key = Integer.parseInt(key_text.getText());
        if (user.equals("Cliente") && nombre.equals("Mario") && key == 1429) {//Usuario y clave para el modulo cliente
            new clientInterface().setVisible(true);
            this.dispose();
        } else if (user.equals("Veterinario") && nombre.equals("David") && key == 1110) {//Usuario y clave para el modulo veterinario
            new vetInterface().setVisible(true);
            this.dispose();
        } else if (user.equals("Administrador") && nombre.equals("Juan") && key == 1415) {//Ususario y clave para el modulo administrador
            new adminInterface().setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos, digite nuevamente");
        }
    }//GEN-LAST:event_singInbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginInterface(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel card_content;
    private javax.swing.JTextField key_text;
    private javax.swing.JLabel key_tittle;
    private javax.swing.JPanel login_section;
    private javax.swing.JLabel login_tittle;
    private javax.swing.JTextField name_text;
    private javax.swing.JLabel name_tittle;
    private javax.swing.JLabel singIn_title;
    private javax.swing.JPanel singInbutton;
    // End of variables declaration//GEN-END:variables
}
