/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author juanq
 */
public class clientInterface extends javax.swing.JFrame {

    /**
     * Creates new form clientInterface
     */
    public clientInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        main_tittle = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        showName = new javax.swing.JLabel();
        reg_title = new javax.swing.JLabel();
        ccOnwer_title = new javax.swing.JLabel();
        petName_title = new javax.swing.JLabel();
        petRace_title = new javax.swing.JLabel();
        petColor_title = new javax.swing.JLabel();
        bornDate_title = new javax.swing.JLabel();
        ccOwnerTextField = new javax.swing.JTextField();
        petNameTextField = new javax.swing.JTextField();
        petColorTextField = new javax.swing.JTextField();
        petRaceTextField = new javax.swing.JTextField();
        bornDateTextField = new javax.swing.JTextField();
        registry_button = new javax.swing.JPanel();
        registry_title = new javax.swing.JLabel();
        dateRequest_button = new javax.swing.JPanel();
        dateRequest_title = new javax.swing.JLabel();
        modifyDate_button = new javax.swing.JPanel();
        modifyDate_title = new javax.swing.JLabel();
        cancelDate_button = new javax.swing.JPanel();
        cancelDate_title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        content.setBackground(new java.awt.Color(255, 255, 255));

        main_tittle.setBackground(new java.awt.Color(8, 156, 255));

        tittle.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        tittle.setText("BIENVENIDO");
        main_tittle.add(tittle);

        showName.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        main_tittle.add(showName);

        reg_title.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        reg_title.setText("Registro");

        ccOnwer_title.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        ccOnwer_title.setText("Cédula del dueño");

        petName_title.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        petName_title.setText("Nombre del perro");

        petRace_title.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        petRace_title.setText("Raza");

        petColor_title.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        petColor_title.setText("Color ");

        bornDate_title.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        bornDate_title.setText("Fecha Nacimiento");

        ccOwnerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccOwnerTextFieldActionPerformed(evt);
            }
        });

        petNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petNameTextFieldActionPerformed(evt);
            }
        });

        petColorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petColorTextFieldActionPerformed(evt);
            }
        });

        petRaceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petRaceTextFieldActionPerformed(evt);
            }
        });

        bornDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bornDateTextFieldActionPerformed(evt);
            }
        });

        registry_button.setBackground(new java.awt.Color(8, 156, 255));
        registry_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registry_buttonMouseClicked(evt);
            }
        });

        registry_title.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        registry_title.setText("Registrar");
        registry_button.add(registry_title);

        dateRequest_button.setBackground(new java.awt.Color(8, 156, 255));
        dateRequest_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateRequest_buttonMouseClicked(evt);
            }
        });

        dateRequest_title.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        dateRequest_title.setText("Solicitar cita");
        dateRequest_button.add(dateRequest_title);

        modifyDate_button.setBackground(new java.awt.Color(8, 156, 255));
        modifyDate_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyDate_buttonMouseClicked(evt);
            }
        });

        modifyDate_title.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        modifyDate_title.setText("Modificar cita");
        modifyDate_button.add(modifyDate_title);

        cancelDate_button.setBackground(new java.awt.Color(8, 156, 255));
        cancelDate_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelDate_buttonMouseClicked(evt);
            }
        });

        cancelDate_title.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        cancelDate_title.setText("Cancelar Cita");
        cancelDate_button.add(cancelDate_title);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_tittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(ccOnwer_title)
                        .addGap(83, 83, 83)
                        .addComponent(petName_title))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(petColorTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(ccOwnerTextField))
                        .addGap(46, 46, 46)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(petNameTextField)
                            .addComponent(petRaceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(reg_title, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(petColor_title)
                        .addGap(159, 159, 159)
                        .addComponent(petRace_title)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                        .addComponent(dateRequest_button, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modifyDate_button, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelDate_button, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(bornDate_title))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(bornDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(registry_button, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addComponent(main_tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reg_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ccOnwer_title)
                        .addComponent(petName_title))
                    .addComponent(dateRequest_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ccOwnerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(petNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(petColor_title)
                            .addComponent(petRace_title)))
                    .addComponent(modifyDate_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(cancelDate_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(petColorTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(petRaceTextField))))
                .addGap(18, 18, 18)
                .addComponent(bornDate_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bornDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(registry_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ccOwnerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccOwnerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccOwnerTextFieldActionPerformed

    private void petNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petNameTextFieldActionPerformed

    private void petColorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petColorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petColorTextFieldActionPerformed

    private void petRaceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petRaceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petRaceTextFieldActionPerformed

    private void bornDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bornDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bornDateTextFieldActionPerformed

    private void registry_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registry_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registry_buttonMouseClicked

    private void dateRequest_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateRequest_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dateRequest_buttonMouseClicked

    private void modifyDate_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyDate_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyDate_buttonMouseClicked

    private void cancelDate_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelDate_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelDate_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bornDateTextField;
    private javax.swing.JLabel bornDate_title;
    private javax.swing.JPanel cancelDate_button;
    private javax.swing.JLabel cancelDate_title;
    private javax.swing.JLabel ccOnwer_title;
    private javax.swing.JTextField ccOwnerTextField;
    private javax.swing.JPanel content;
    private javax.swing.JPanel dateRequest_button;
    private javax.swing.JLabel dateRequest_title;
    private javax.swing.JPanel main_tittle;
    private javax.swing.JPanel modifyDate_button;
    private javax.swing.JLabel modifyDate_title;
    private javax.swing.JTextField petColorTextField;
    private javax.swing.JLabel petColor_title;
    private javax.swing.JTextField petNameTextField;
    private javax.swing.JLabel petName_title;
    private javax.swing.JTextField petRaceTextField;
    private javax.swing.JLabel petRace_title;
    private javax.swing.JLabel reg_title;
    private javax.swing.JPanel registry_button;
    private javax.swing.JLabel registry_title;
    private javax.swing.JLabel showName;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
